# ./.github/workflows/publish.yml
name: Publish

on:
  push:
    tags:
      - event-flow@*.*.*
      - elements@*.*.*
      - utils@*.*.*
      - di@*.*.*

permissions:
  actions: read
  contents: read

jobs:
  test:
    name: Publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # needed for provenance data generation
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Set up pnpm and node so that we can verify our setup and that the NPM_TOKEN secret will work later
      - uses: pnpm/action-setup@v4
        with:
          version: 8

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
          check-latest: true
          cache: 'pnpm'

      # Ensure that the NPM_TOKEN secret is still valid before wasting any time deriving data or building projects
      - name: Check NPM Credentials
        run: npm whoami && echo "NPM credentials are valid" || (echo "NPM credentials are invalid or have expired." && exit 1)

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        shell: bash

      - name: Print Environment Info
        run: pnpx nx report
        shell: bash

      - name: Publish packages
        run: pnpx nx release publish
        shell: bash
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
          NPM_CONFIG_PROVENANCE: true
